server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql:///test3
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: usertest
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
mybatis:
  type-aliases-package: com.offcn.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka